declare var gg_rct_Boss_Spawn: rect;
declare var gg_rct_FightStart: rect;
declare var gg_rct_PlayerOneSpawn: rect;
declare var gg_rct_StatueNE: rect;
declare var gg_rct_StatueNW: rect;
declare var gg_rct_StatueSE: rect;
declare var gg_rct_StatueSW: rect;
declare var gg_trg_Untitled_Trigger_001: trigger;
declare var gg_rct_PlayerTwoSpawn: rect;
